FROM rayproject/ray:2.3.0-py310

WORKDIR /app
COPY combined_ray_wo_fastapi.py requirements.txt synset.txt  ./

RUN pip install --no-cache-dir -r requirements.txt
RUN pip uninstall -y pydantic && pip install pydantic==1.10.8

ENV PYTHONPATH=/app:$PYTHONPATH

EXPOSE 8000 8265

WORKDIR /app
# CMD ["python","combined_ray.py"]

# CMD ["python","ray_triton_app.py"]
